apiVersion: v1
kind: Secret
metadata:
  name: payment-platform-secrets
stringData:
  DATABASE_URL: postgres://payment:payment@postgres:5432/payments?sslmode=disable
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  CLICKHOUSE_PASSWORD: analytics
