apiVersion: v1
kind: Secret
metadata:
  name: payment-platform-infrastructure-secrets
stringData:
  POSTGRES_DB: payments
  POSTGRES_USER: payment
  POSTGRES_PASSWORD: payment
  KEYCLOAK_DB_PASSWORD: keycloak
  KEYCLOAK_ADMIN_USER: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  TEMPORAL_DB_PASSWORD: temporal
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
